/// Flutter icons QJay
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  QJay
///      fonts:
///       - asset: fonts/QJay.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class QJay {
  QJay._();

  static const _kFontFam = 'QJay';
  static const String? _kFontPkg = null;

  static const IconData qs_logo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
